### ISSUE TITLE
Use correctly /etc/sysconfig and /etc/default env defaults

### ISSUE THREAD

**Issue by arm4b** [StackStorm/st2chatops#50]
There are places for default env variables in different distro families: 
- `/etc/sysconfig` - for Red Hat-like
- `/etc/default` - for debian-like

We support them in init files: 
https://github.com/StackStorm/st2chatops/blob/master/debian/st2chatops.upstart#L24
https://github.com/StackStorm/st2chatops/blob/master/rpm/st2chatops.service#L10

So [`st2chatops.env`](https://github.com/StackStorm/st2chatops/blob/master/st2chatops.env) should not overwrite env variable, if it was already passed.
The good example is: https://github.com/StackStorm/st2chatops/blob/master/st2chatops.env#L1
```
export ST2_HOSTNAME="${ST2_HOSTNAME:-localhost}"
```

^^ Do that for _every other_ env variable in `st2chatops.env` as a rule.

---

Ideally, apart of editing existing `st2chatops.env` ([`sed`-like stuff](https://github.com/StackStorm/st2-packages/blob/b7865ab6a0e70eb4d09a3f40279a4953e2640c0d/scripts/st2bootstrap-deb.sh#L300-L312) is error-prone) user can just place his custom variables (good to do with Configuration Management tools) in `/etc/sysconfig/st2chatops` or `/etc/default/st2chatops` and be sure that they're used as a priority.

**Comment by cognifloyd** [comment]
Currently it is also impossible to override most of the vars in `st2chatops.env` when running `bin/hubot` from the command line because of https://github.com/StackStorm/st2chatops/blob/9066a1fed83615fa13b19985c546e9621b612cc0/bin/hubot#L15

In the smoke tests of the ansible-st2 playbook, essentially, we run:

```
HUBOT_LOG_LEVEL=debug timeout 10 bash -c '(sleep 5; echo exit ) | bin/hubot'
```

Note that I don't think defining the variables with a bash default is sufficient, even though this it would allow overriding the variables from the command line: https://github.com/StackStorm/st2chatops/blob/9066a1fed83615fa13b19985c546e9621b612cc0/st2chatops.env#L1

That's not enough because it would make handling those settings through configuration management more error prone and problematic. We need a dedicated configuration file for system-specific settings that overrides the default settings in `st2chatops.env`. Putting this system-specific config file in the distro-specific environment variables file makes sense to me.

Please change the implementation of `bin/hubot` to support setting the variables outside of `st2chatops.env` including from the command line (for testing purposes) and from distro-specific environment variable files.
