### ISSUE TITLE
Need updated hubot-slack once they release 4.0.2

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2chatops#56]
The hubot slack adapter has had a fix for usernames with . or - merged to master, but not part part of a release yet.

https://github.com/slackhq/hubot-slack/pull/310

Thanks

**Comment by peschmae** [comment]
Are there currently any plans, to go forward with a hubot-slack upgrade?

In July 2016 there was a bugfix merged, which fixes a disconnection issue in hubot-slack, which would improve the reliability of Stackstorm/Slack a lot.
slackapi/hubot-slack/issues/203

**Comment by ytjohn** [comment]
I'm going to pop on here as well.  Because I needed a fix to allow an https_proxy to reach slack, I had to pull in 4.3.3 and that seems to work fine for me so far. Technically, what I need is `@slack/client@3.8.1`, which 4.3.3 pulls in. 

https://github.com/slackapi/node-slack-sdk/issues/268
https://github.com/slackapi/node-slack-sdk/pull/271/files

```
├─┬ hubot-slack@4.3.3
│ ├─┬ @slack/client@3.8.1
├─┬ slack-client@1.4.1
```

https://github.com/StackStorm/st2docs/issues/418

**Comment by joanmarcriera** [comment]
I also need this. :)
